# Generated by Django 5.0.6 on 2024-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Umumiy kurs narxi', max_digits=10),
        ),
    ]
