# Generated by Django 5.0.6 on 2024-06-11 05:49

import course.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_quantity_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='Kurs nomi', null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Videolar', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonvideo',
            name='video',
            field=models.FileField(upload_to='lesson/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv']), course.models.file_size]),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Kurslar', to='course.category'),
        ),
    ]
