# Generated by Django 5.0.6 on 2024-06-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='course',
        ),
        migrations.AddField(
            model_name='usercomments',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
            preserve_default=False,
        ),
    ]
