# Generated by Django 5.0.6 on 2024-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_usercomments_course_usercomments_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='mark',
            field=models.ImageField(default=1, max_length=5, upload_to=''),
            preserve_default=False,
        ),
    ]
