# Generated by Django 5.0.6 on 2024-06-11 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_usercomments_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
