# Generated by Django 5.0.6 on 2024-06-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_usercomments_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='mark',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
