# Generated by Django 5.0.6 on 2024-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_usercomments_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMassege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
