# Generated by Django 5.0.6 on 2024-06-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_sendmassage_delete_sendmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendmassage',
            old_name='message',
            new_name='massage',
        ),
    ]
