# Generated by Django 5.0.6 on 2024-06-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_message_sendmassage_massage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendMassage',
        ),
    ]
